spring:
  config:
    activate:
      on-profile: prod
    import: optional:dotenv:.

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: 8080

file:
  upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}

storage:
  type: ${STORAGE_TYPE:local}
  local:
    root-path: ${STORAGE_LOCAL_ROOT_PATH:/app/uploads}

aws:
  access-key: ${AWS_S3_ACCESS_KEY}
  secret-key: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

logging:
  level:
    com.codeit.blog: INFO
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework.web: info

app:
  frontend:
    auth-success-url: ${SUCCESS_REDIRECT_URL:http://localhost:8080/#/oauth/callback}
    auth-failure-url: ${SUCCESS_REDIRECT_URL:http://localhost:8080/#/auth/error}
  jwt:
    access-expire-ms: ${ACCESS_EXPIRE_MS:1800000}      # 30분
    refresh-expire-ms: ${REFRESH_EXPIRE_MS:1209600000} # 14일
  cookie:
    secure: true
    same-site: Lax
    refresh-max-age: ${REFRESH_MAX_AGE:1209600}        # 14일(초)
