spring:
  application:
    name: read-compass
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: secret

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC
    open-in-view: false

# log
logging:
  level:
    root: info
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"

read-compass:
  storage:
    local:
      root-path: .read-compass/storage

app:
  jwt:
    access-expire-ms: ${ACCESS_EXPIRE_MS:600000}      # 기본 10분
    refresh-expire-ms: ${REFRESH_EXPIRE_MS:86400000}  # 기본 1일
  cookie:
    refresh-max-age: ${REFRESH_MAX_AGE:86400}          # 기본 1일(초)
